/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: catzer (https://sketchfab.com/catzer)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/small-stylized-house-be5c115c4dca494881b87409e6246289
title: Small Stylized House
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/house2.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.aiStandardSurface1SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/house2.gltf')
