/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Pooi Woon Hoh (https://sketchfab.com/Koha.Ha)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-sweet-home-23c9d40a516f47b890e120abf78b8336
title: Low Poly Sweet Home
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/house1.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.polySurface8_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface7_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface9_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <group position={[-4.31, 0, 0.77]} rotation={[Math.PI, 0, -3.12]}>
            <mesh geometry={nodes.polySurface159_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          </group>
          <mesh geometry={nodes.polySurface1_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface35_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface34_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface30_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface28_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface29_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface37_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface38_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface31_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface36_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface24_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface25_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface27_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface26_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface51_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface52_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface42_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface44_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface43_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface39_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface40_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface41_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface57_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface59_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface58_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface60_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface54_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface55_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface56_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface75_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface79_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface77_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface74_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface78_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface80_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface76_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface14_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface16_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface15_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface17_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface18_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface12_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface11_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface13_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface32_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface10_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface71_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface72_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface73_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface67_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface68_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface69_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface70_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface23_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface19_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface20_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface21_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface22_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface65_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface66_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface64_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface63_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface61_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface62_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface155_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface156_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface158_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface136_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface137_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface153_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface152_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface138_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface139_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface147_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface146_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface140_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface141_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface142_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface143_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface144_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface145_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface149_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface148_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface135_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface150_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface151_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface134_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface133_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface132_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface131_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface130_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface126_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface127_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface128_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface129_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface123_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface125_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface124_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface122_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface121_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface118_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface119_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface120_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface154_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <group position={[0.02, -0.04, -0.03]} rotation={[0.02, 0, 0]}>
            <group position={[0, 0.05, 0.44]} rotation={[-0.07, 0, 0]}>
              <mesh geometry={nodes.polySurface99_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.05, 0.44]} rotation={[-0.07, 0, 0]}>
              <mesh geometry={nodes.polySurface116_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.05, 0.44]} rotation={[-0.07, 0, 0]}>
              <mesh geometry={nodes.polySurface100_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.05, 0.33]} rotation={[-0.06, 0, 0]}>
              <mesh geometry={nodes.polySurface101_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.05, 0.33]} rotation={[-0.06, 0, 0]}>
              <mesh geometry={nodes.polySurface102_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.05, 0.33]} rotation={[-0.06, 0, 0]}>
              <mesh geometry={nodes.polySurface109_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.17, 0.54]} rotation={[-0.14, 0, 0]}>
              <mesh geometry={nodes.polySurface108_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.17, 0.54]} rotation={[-0.14, 0, 0]}>
              <mesh geometry={nodes.polySurface107_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.11, 0.5]} rotation={[-0.11, 0, 0]}>
              <mesh geometry={nodes.polySurface103_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.11, 0.5]} rotation={[-0.11, 0, 0]}>
              <mesh geometry={nodes.polySurface104_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.11, 0.5]} rotation={[-0.11, 0, 0]}>
              <mesh geometry={nodes.polySurface105_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.11, 0.5]} rotation={[-0.11, 0, 0]}>
              <mesh geometry={nodes.polySurface106_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.05, 0.33]} rotation={[-0.06, 0, 0]}>
              <mesh geometry={nodes.polySurface110_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.01, 0]} rotation={[-0.01, 0, 0]}>
              <group position={[0, 0.08, 0.51]} rotation={[-0.19, 0, 0]}>
                <mesh geometry={nodes.polySurface98_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              </group>
              <group position={[0, 0.08, 0.51]} rotation={[-0.19, 0, 0]}>
                <mesh geometry={nodes.polySurface113_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              </group>
              <group position={[0, 0.08, 0.51]} rotation={[-0.19, 0, 0]}>
                <mesh geometry={nodes.polySurface114_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              </group>
              <group position={[0, 0.08, 0.51]} rotation={[-0.19, 0, 0]}>
                <mesh geometry={nodes.polySurface97_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              </group>
              <mesh geometry={nodes.polySurface93_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface94_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface95_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface96_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface91_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface85_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface89_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface90_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface87_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface88_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface86_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface92_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface83_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface81_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface84_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface82_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
              <mesh geometry={nodes.polySurface117_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.05, 0.44]} rotation={[-0.07, 0, 0]}>
              <mesh geometry={nodes.polySurface115_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.17, 0.54]} rotation={[-0.14, 0, 0]}>
              <mesh geometry={nodes.polySurface111_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
            <group position={[0, 0.17, 0.54]} rotation={[-0.14, 0, 0]}>
              <mesh geometry={nodes.polySurface112_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            </group>
          </group>
          <mesh geometry={nodes.polySurface50_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface49_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface47_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface5_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface45_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface33_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface6_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface4_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface3_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface2_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.polySurface48_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/house1.gltf')
