/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Kenny Kwok. (https://sketchfab.com/motpanda)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/little-pond-fish-4f091bcb17ce42ee9a7e678a16ddc349
title: Little Pond & fish
*/

import React, { useState, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/littlepond.gltf')
  const { actions, names } = useAnimations(animations, group)

  const [index, setIndex] = useState(0)

useEffect(() => {
  actions[names[index]].play()
})

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="256ae75f916e40e78ac973ba22dbb243fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Pond">
                  <group name="pCube2" position={[1.29, 0.16, 2.37]} scale={[0.22, 0.05, 1.35]}>
                    <mesh name="pCube2_Default_Material_0" geometry={nodes.pCube2_Default_Material_0.geometry} material={materials.Default_Material} />
                  </group>
                  <group name="pCube3" position={[3.82, 0.16, 2.37]} rotation={[0, 0, Math.PI]} scale={[0.22, 0.05, 1.35]}>
                    <mesh name="pCube3_Default_Material_0" geometry={nodes.pCube3_Default_Material_0.geometry} material={materials.Default_Material} />
                  </group>
                  <group name="pCube4" position={[2.05, 0.16, 2.37]} scale={[0.11, 0.02, 0.72]}>
                    <mesh name="pCube4_Default_Material_0" geometry={nodes.pCube4_Default_Material_0.geometry} material={materials.Default_Material} />
                  </group>
                  <group name="pCube5" position={[2.97, 0.16, 2.37]} rotation={[0, 0, Math.PI]} scale={[0.11, 0.02, 0.72]}>
                    <mesh name="pCube5_Default_Material_0" geometry={nodes.pCube5_Default_Material_0.geometry} material={materials.Default_Material} />
                  </group>
                  <group name="ani_01_n_pond_pulsepCube2" position={[1.29, 0.16, 2.37]} scale={[0.22, 0.05, 1.35]}>
                    <mesh name="ani_01_n_pond_pulsepCube2_Default_Material_0" geometry={nodes.ani_01_n_pond_pulsepCube2_Default_Material_0.geometry} material={materials.Default_Material} />
                  </group>
                  <group name="ani_01_n_pond_pulsepCube3" position={[3.82, 0.16, 2.37]} rotation={[0, 0, Math.PI]} scale={[0.22, 0.05, 1.35]}>
                    <mesh name="ani_01_n_pond_pulsepCube3_wave_0" geometry={nodes.ani_01_n_pond_pulsepCube3_wave_0.geometry} material={materials.wave} />
                  </group>
                  <group name="ani_01_n_pond_pulsepCube4" position={[2.05, 0.16, 2.37]} scale={[0.11, 0.02, 0.72]}>
                    <mesh name="ani_01_n_pond_pulsepCube4_wave_0" geometry={nodes.ani_01_n_pond_pulsepCube4_wave_0.geometry} material={materials.wave} />
                  </group>
                  <group name="ani_01_n_pond_pulsepCube5" position={[2.97, 0.16, 2.37]} rotation={[0, 0, Math.PI]} scale={[0.11, 0.02, 0.72]}>
                    <mesh name="ani_01_n_pond_pulsepCube5_wave_0" geometry={nodes.ani_01_n_pond_pulsepCube5_wave_0.geometry} material={materials.wave} />
                  </group>
                  <group name="ani_01_n_pond_pulse1pCube2" position={[1.29, 0.16, 2.37]} scale={[0.22, 0.05, 1.35]}>
                    <mesh name="ani_01_n_pond_pulse1pCube2_wave_0" geometry={nodes.ani_01_n_pond_pulse1pCube2_wave_0.geometry} material={materials.wave} />
                  </group>
                  <group name="ani_01_n_pond_pulse1pCube3" position={[3.82, 0.16, 2.37]} rotation={[0, 0, Math.PI]} scale={[0.22, 0.05, 1.35]}>
                    <mesh name="ani_01_n_pond_pulse1pCube3_Default_Material_0" geometry={nodes.ani_01_n_pond_pulse1pCube3_Default_Material_0.geometry} material={materials.Default_Material} />
                  </group>
                  <group name="ani_01_n_pond_pulse1pCube4" position={[2.05, 0.16, 2.37]} scale={[0.11, 0.02, 0.72]}>
                    <mesh name="ani_01_n_pond_pulse1pCube4_Default_Material_0" geometry={nodes.ani_01_n_pond_pulse1pCube4_Default_Material_0.geometry} material={materials.Default_Material} />
                  </group>
                  <group name="ani_01_n_pond_pulse1pCube5" position={[2.97, 0.16, 2.37]} rotation={[0, 0, Math.PI]} scale={[0.11, 0.02, 0.72]}>
                    <mesh name="ani_01_n_pond_pulse1pCube5_Default_Material_0" geometry={nodes.ani_01_n_pond_pulse1pCube5_Default_Material_0.geometry} material={materials.Default_Material} />
                  </group>
                  <group name="pCube6" position={[-4.72, 0.16, -4.38]} scale={[0.15, 0.03, 0.92]}>
                    <mesh name="pCube6_wave_0" geometry={nodes.pCube6_wave_0.geometry} material={materials.wave} />
                  </group>
                  <group name="pCube7" position={[-3.33, 0.16, -4.38]} rotation={[0, 0, Math.PI]} scale={[0.15, 0.03, 0.92]}>
                    <mesh name="pCube7_wave_0" geometry={nodes.pCube7_wave_0.geometry} material={materials.wave} />
                  </group>
                  <group name="pCube8" position={[-4.47, 0.07, -4.4]} scale={[0.06, 0.02, 0.57]}>
                    <mesh name="pCube8_wave_0" geometry={nodes.pCube8_wave_0.geometry} material={materials.wave} />
                  </group>
                  <group name="pCube9" position={[-3.61, 0.07, -4.4]} rotation={[0, 0, Math.PI]} scale={[0.04, 0.02, 0.57]}>
                    <mesh name="pCube9_wave_0" geometry={nodes.pCube9_wave_0.geometry} material={materials.wave} />
                  </group>
                  <group name="pSphere8" position={[-3.48, 0.18, 3.49]} scale={0}>
                    <mesh name="pSphere8_wave_0" geometry={nodes.pSphere8_wave_0.geometry} material={materials.wave} />
                  </group>
                  <group name="pSphere9" position={[-1.86, -0.28, 4.28]} scale={0.1}>
                    <mesh name="pSphere9_wave_0" geometry={nodes.pSphere9_wave_0.geometry} material={materials.wave} />
                  </group>
                  <group name="pSphere10" position={[-2.41, 0.53, 2.83]} scale={0}>
                    <mesh name="pSphere10_wave_0" geometry={nodes.pSphere10_wave_0.geometry} material={materials.wave} />
                  </group>
                  <group name="group5" position={[2.49, -1.69, -1.53]} rotation={[-Math.PI, 1.07, -Math.PI]}>
                    <group name="Object_254">
                      <group name="rig_01_n_pond_fishpolySurface2" position={[0.43, -0.04, 0]} rotation={[-0.41, 0.44, 0.33]} scale={0.77}>
                        <mesh name="rig_01_n_pond_fishpolySurface2_rig_01_n_pond_fishfishhead_0" geometry={nodes.rig_01_n_pond_fishpolySurface2_rig_01_n_pond_fishfishhead_0.geometry} material={materials.rig_01_n_pond_fishfishhead} />
                      </group>
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh name="Object_257" geometry={nodes.Object_257.geometry} material={materials.rig_01_n_pond_fishfisheye} skeleton={nodes.Object_257.skeleton} />
                      <skinnedMesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials.rig_01_n_pond_fishfishhead} skeleton={nodes.Object_258.skeleton} />
                      <skinnedMesh name="Object_259" geometry={nodes.Object_259.geometry} material={materials.rig_01_n_pond_fishfishbody} skeleton={nodes.Object_259.skeleton} />
                    </group>
                  </group>
                  <group name="group6" position={[-3.17, -2.65, 2.91]} rotation={[0.08, -0.7, -0.04]}>
                    <group name="Object_290">
                      <group name="rig_01_n_pond_fish1polySurface2" position={[0.37, 0.07, -0.02]} rotation={[-0.3, -0.21, 0.44]} scale={0.77}>
                        <mesh name="rig_01_n_pond_fish1polySurface2_rig_01_n_pond_fish1fishhead_0" geometry={nodes.rig_01_n_pond_fish1polySurface2_rig_01_n_pond_fish1fishhead_0.geometry} material={materials.rig_01_n_pond_fish1fishhead} />
                      </group>
                      <primitive object={nodes._rootJoint_1} />
                      <skinnedMesh name="Object_293" geometry={nodes.Object_293.geometry} material={materials.rig_01_n_pond_fish1fisheye} skeleton={nodes.Object_293.skeleton} />
                      <skinnedMesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials.rig_01_n_pond_fish1fishhead} skeleton={nodes.Object_294.skeleton} />
                      <skinnedMesh name="Object_295" geometry={nodes.Object_295.geometry} material={materials.rig_01_n_pond_fish1fishbody} skeleton={nodes.Object_295.skeleton} />
                    </group>
                  </group>
                  <group name="group7" position={[-3.03, -1.83, 0.03]} rotation={[-0.12, 0.59, 0.11]} scale={0.69}>
                    <group name="Object_326">
                      <group name="rig_01_n_pond_fish2polySurface2" position={[0.39, -0.07, 0.02]} rotation={[-0.29, 0.41, -0.02]} scale={0.77}>
                        <mesh name="rig_01_n_pond_fish2polySurface2_rig_01_n_pond_fish2fishhead_0" geometry={nodes.rig_01_n_pond_fish2polySurface2_rig_01_n_pond_fish2fishhead_0.geometry} material={materials.rig_01_n_pond_fish2fishhead} />
                      </group>
                      <primitive object={nodes._rootJoint_2} />
                      <skinnedMesh name="Object_329" geometry={nodes.Object_329.geometry} material={materials.rig_01_n_pond_fish2fisheye} skeleton={nodes.Object_329.skeleton} />
                      <skinnedMesh name="Object_330" geometry={nodes.Object_330.geometry} material={materials.rig_01_n_pond_fish2fishhead} skeleton={nodes.Object_330.skeleton} />
                      <skinnedMesh name="Object_331" geometry={nodes.Object_331.geometry} material={materials.rig_01_n_pond_fish2fishbody} skeleton={nodes.Object_331.skeleton} />
                    </group>
                  </group>
                  <group name="pCube1" scale={[11.38, 0.88, 15.76]}>
                    <mesh name="pCube1_pondbase_0" geometry={nodes.pCube1_pondbase_0.geometry} material={materials.pondbase} />
                    <mesh name="pCube1_lambert6_0" geometry={nodes.pCube1_lambert6_0.geometry} material={materials.lambert6} />
                  </group>
                  <group name="pPlane1" scale={20.16}>
                    <mesh name="pPlane1_water_0" geometry={nodes.pPlane1_water_0.geometry} material={materials.water} />
                  </group>
                  <group name="pSphere4" position={[3.67, -3.85, -8.8]} rotation={[0, 0.66, 0]} scale={[0.87, 0.52, 0.87]}>
                    <mesh name="pSphere4_lambert6_0" geometry={nodes.pSphere4_lambert6_0.geometry} material={materials.lambert6} />
                  </group>
                  <group name="pSphere5" position={[5.29, -3.85, -7.75]} rotation={[0, 0.66, 0]} scale={[1.28, 0.76, 1.28]}>
                    <mesh name="pSphere5_lambert6_0" geometry={nodes.pSphere5_lambert6_0.geometry} material={materials.lambert6} />
                  </group>
                  <group name="pSphere6" position={[-4.63, -3.36, 4.48]} rotation={[0, 0.66, 0]} scale={[0.57, 0.34, 0.57]}>
                    <mesh name="pSphere6_lambert6_0" geometry={nodes.pSphere6_lambert6_0.geometry} material={materials.lambert6} />
                  </group>
                  <group name="pSphere7" position={[-3.01, -3.36, 5.53]} rotation={[0, 0.66, 0]} scale={[0.84, 0.5, 0.84]}>
                    <mesh name="pSphere7_lambert6_0" geometry={nodes.pSphere7_lambert6_0.geometry} material={materials.lambert6} />
                  </group>
                  <group name="_GrasspolySurface2">
                    <mesh name="_GrasspolySurface2_grass03_0" geometry={nodes._GrasspolySurface2_grass03_0.geometry} material={materials.grass03} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/littlepond.gltf')
