/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Shelest (https://sketchfab.com/shelest)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/nixie-tube-5c984fafecb7408db6f6097a929e6f18
title: Nixie tube
*/

import * as THREE from 'three';
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei';

const glowGreen = new THREE.MeshBasicMaterial({ color: new THREE.Color(0, 3, 1), toneMapped: false })


const Tube = (props) => {
  const { nodes, materials } = useGLTF('/tube.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 5.74, 0.08]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={glowGreen} />
          </group>
          <group position={[0, 5.74, 0.08]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={glowGreen} />
          </group>
          <group position={[0, 5.74, 0.08]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={glowGreen} />
          </group>
          <group position={[0, 3.59, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.glass_4096} />
          </group>
          <group position={[0, 3.59, 0.3]} rotation={[Math.PI / 2, 0, 0]} scale={7.71}>
            <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.anode_2048_4096} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.grid_4096} />
          </group>
          <group position={[0, 3.74, -0.41]} rotation={[-Math.PI / 2, 0, 0]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_6.geometry} material={glowGreen} />
          </group>
          <group position={[0, 3.29, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_7.geometry} material={glowGreen} />
          </group>
          <group position={[0, 3.29, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_8.geometry} material={glowGreen} />
          </group>
          <group position={[0, 5.74, -0.37]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.dot_r} />
          </group>
          <group position={[0, 5.74, -0.37]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.dot_l} />
          </group>
          <group position={[0, 5.74, -0.41]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials['1_2048_4096']} />
          </group>
          <group position={[0, 5.74, -0.41]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials['2_2048_4096']} />
          </group>
          <group position={[0, 5.74, -0.41]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials['3_2048_4096']} />
          </group>
          <group position={[0, 5.74, -0.41]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials['4_2048_4096']} />
          </group>
          <group position={[0, 5.74, -0.41]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials['5_2048_4096']} />
          </group>
          <group position={[0, 5.74, -0.41]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials['6_2048_4096']} />
          </group>
          <group position={[0, 5.74, -0.41]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials['8_2048_4096']} />
          </group>
          <group position={[0, 5.74, -0.41]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials['9_2048_4096']} />
          </group>
          <group position={[0, 5.74, -0.41]} scale={6.54}>
            <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials['0_2048_4096']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tube.gltf')

export default Tube;
